sudo: required
services:
  - docker

before_install:
  - docker build -t zargham/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zargham/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "ëu-west-3"
  app: "docker-react" 
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-159139108037"

  on:
    branch: master 
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 
 
